version: "3.7"
services:
  web-plan-crecimiento:
    container_name: cn_plan_crecimiento
    image: kooldev/php:8.2-nginx-sqlsrv-prod
    restart: always
    volumes:
      - "./:/app/crecimiento"
      - "./default.tmpl:/kool/default.tmpl"
    ports:
      - "83:80"
    environment:
      - APP_NAME=crecimiento
      - PHP_FPM_LISTEN=/run/php-fpm.sock
      - NGINX_LISTEN=80
      - NGINX_ROOT=/app/crecimiento/public
      - NGINX_INDEX=index.php
      - NGINX_CLIENT_MAX_BODY_SIZE=25M
      - NGINX_PHP_FPM=unix:/run/php-fpm.sock
      - NGINX_FASTCGI_READ_TIMEOUT=60s
      - NGINX_FASTCGI_BUFFERS=8 8k
      - NGINX_FASTCGI_BUFFER_SIZE=16k